### ISSUE TITLE
stratified: complex compounds disappear leaving dangling nodes behind

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/viewer-component#8]
Try this:

http://beta.pathwaycommons.org/pathways/#/view?uri=http%3A%2F%2Fidentifiers.org%2Freactome%2FR-HSA-111463

- expand some complex nodes and apply different layouts; 'stratified' results in complex compound nodes disappear and disconnected complex-member nodes.

**Comment by d2fong** [comment]
Current half-fix -- collapse all nodes before performing stratification. https://github.com/PathwayCommons/pathways-search/commit/f3bcdd12343616b907b1dbeebf2624dcb63b5deb

It would probably be better to expand the same nodes after stratification but it seems that the expand collapse extension throws an error for that.  I am not sure why. 

We can create a new issue if we want expanded nodes to be expanded again after stratification, but this should fix node relationships disappearing
